# Generated by Django 5.0.2 on 2024-03-05 12:23

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_image_owner'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', app.models.UserManager()),
            ],
        ),
    ]
